In [ ]:
#BLM KELAR

In [19]:
from gensim.models import FastText

In [20]:
kalimat = []
for i in range(0,300):
    teks = open(str(i)+".txt").readlines()
    kalimat.append(teks)

In [21]:
kalimat = [kalimat[i][0].split() for i in range(len(kalimat))]

In [22]:
max_n = max([len(i) for i in kalimat])
max_n

7

In [23]:
kalimat

[['pohon', 'banyak', 'kanan', 'banyak', 'tinggi'],
 ['kau', 'ingin', 'kecil'],
 ['penyemangatku', 'happy', 'gampang', 'akulah'],
 ['di', 'jauh', 'aku', 'tempat', 'kecil', 'langit'],
 ['angkasa', 'angkasa', 'ke'],
 ['kecil', 'terbang', 'berada', 'biru', 'bintang', 'di', 'terbang'],
 ['ayam', 'happy', 'sapi'],
 ['berada', 'terbang', 'langit', 'dan', 'langit'],
 ['cemara', 'cemara', 'sekali', 'cemara', 'puncak'],
 ['langit', 'banyak', 'jauh', 'langit'],
 ['hidupku', 'kuat', 'kuat'],
 ['aku', 'biru', 'angkasa'],
 ['yang', 'tempat', 'ke', 'kecil', 'amat'],
 ['akulah', 'ayam', 'ku', 'hidupku', 'kasar'],
 ['ngguyu', 'ku', 'aku', 'adalah', 'hidupku'],
 ['ke', 'pohon', 'kulihat', 'kulihat', 'naik'],
 ['ke', 'banyak', 'yang'],
 ['aku', 'aku', 'angkasa', 'berada', 'bintang'],
 ['cemara', 'saja', 'sekali'],
 ['kulihat', 'gunung', 'saja', 'sekali'],
 ['kulihat', 'sekali', 'kanan', 'naik'],
 ['cemara', 'naik', 'pohon', 'banyak', 'kulihat'],
 ['banyak', 'yang', 'berada', 'angkasa', 'tinggi', 'kau'],


In [24]:
corpus = kalimat
model = FastText(vector_size = max_n,
                window = 3,
                min_count = 1,
                sentences = corpus,
                epochs = 10)

In [25]:
model.train(corpus_iterable=corpus, total_examples=len(corpus), epochs=10)

(4179, 14760)

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [34]:
nim_gue = model.wv["pentol"].reshape(1,-1)

In [35]:
nim_gue

array([[-0.08854787,  0.05840404, -0.17343062,  0.2080426 , -0.07802194,
        -0.0242411 ,  0.15993352]], dtype=float32)

In [36]:
idx = []
for i in range(0,300):
    if i == 153:
        pass
    else:
        x = open(str(i)+".txt").readline().strip()
        c = cosine_similarity(nim_gue,model.wv[x].reshape(1,-1))
        idx.append(c[0][0])
    

In [37]:
idx.index(max(idx))

171

In [40]:
open("171.txt").readline()

'ke biru ke angkasa ingin '

In [105]:
print(idx[271])

0.9965703


In [83]:
cosine_similarity(nim_gue,model.wv["langit biru berada biru yang menghias bintang"].reshape(1,-1))

array([[0.98189753]], dtype=float32)

In [106]:
nim_gue

array([[-0.02221973,  0.0267251 , -0.04703705,  0.06308581, -0.02706773,
        -0.01620316,  0.05213752]], dtype=float32)